baseURL = "https://www.grugrut.net"
DefaultContentLanguage = "ja"
title = "ぐるっとぐりっど"
theme = "sauvignon"
disqusShortname = "grugrut"
googleAnalytics = "UA-41607666-9"
enableGitInfo = true
hasCJKLanguage = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  commit = "https://github.com/grugrut/blog/tree/"
  dateFormat = "2006-01-02"
  rss = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  comments = true

[Author]
  name = "Masanori Mano"
  github = "grugrut"
  twitter = "grugrut"

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3

[[menu.main]]
  name = "Archives"
  url = "archives"
  weight = 3

[[menu.main]]
  name = "About"
  url = "about"
  weight = 3

[taxonomies]
tag = "tags"
archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
