baseURL = "https://blog.grugrut.net"
DefaultContentLanguage = "ja"
title = "ぐるっとぐりっど"
theme = "beautifulhugo"
disqusShortname = "grugrut"
googleAnalytics = "UA-41607666-9"
enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  commit = "https://github.com/grugrut/blog/tree/"
  dateFormat = "2006-01-02"
  rss = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  comments = true

[Author]
  name = "grugrut"
  github = "grugrut"
  twitter = "grugrut"

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3
