name = "Grugrut Beautiful Hugo"
license = "MIT"
#licenselink = "https://github.com/halogenica/Hugo-BeautifulHugo/blob/master/LICENSE"
description = "A theme forked from Beautiful Hugo"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
min_version = 0.48

[author]
    name = "grugrut"

# If Porting existing theme
[original]
    name = "halogenica"
    homepage = "http://halogenica.net"
    repo = "https://github.com/halogenica/Hugo-BeautifulHugo"
